utils/daily-mail: handle pipelines with no downstream pipelines
Sometimes, Gitlab CI pipelines will fail even before the downstream
pipeline is triggered. A recent example of this is:

  https://gitlab.com/buildroot.org/buildroot/-/pipelines/973195858

Here, it is the generate-gitlab-ci-yml step that failed with "ERROR:
Job failed: failed to pull image
"registry.gitlab.com/buildroot.org/buildroot/base:20230207.1123"",
which basically is a Gitlab CI infrastructure issue.

Such a pipeline does not have a "downstream_pipeline" causing our
logic to abort with a nice explosion:

Traceback (most recent call last):
  File "/home/buildroot/buildroot-test/utils/daily-mail", line 901, in <module>
    __main__()
  File "/home/buildroot/buildroot-test/utils/daily-mail", line 882, in __main__
    gitlab_ci = loop.run_until_complete(gitlab_ci_get(date_struct, kinds=email_data))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/buildroot/buildroot-test/utils/daily-mail", line 768, in gitlab_ci_get
    pipelines_downstream_ids = await asyncio.gather(*[gitlab_ci_get_downstream_pipeline(pipeline['id'])
  File "/home/buildroot/buildroot-test/utils/daily-mail", line 753, in gitlab_ci_get_downstream_pipeline
    return json[0]["downstream_pipeline"]["id"]
TypeError: 'NoneType' object is not subscriptable

We fix that by:

(1) Properly handling the case of a pipeline with no downstream
    pipeline in gitlab_ci_get_downstream_pipeline(): we return a
    "None" as the downstream pipeline id

(2) By filtering such bogus pipelines in gitlab_ci_get(), by dropping
    the pipelines that have "None" as their downstream pipeline id.

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>